name: Build
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 21 ]
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - name: JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Setup Gradle 8.10
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.10" # Quotes required to prevent YAML converting to number
      - name: Build with Gradle 8.10
        run: gradle build
